name: first-exercise-workflow
on: [push, pull_request]

jobs:
  confirm-cmd-job:
    runs-on: ubuntu-latest
    steps:
      - name: run multiple command
        run: |
          python --version
          pip --version